#pragma once
#include <dctl/successor/copy/primary_fwd.hpp>
#include <dctl/successor/copy/primary.hpp>
#include <dctl/successor/copy/legal.hpp>
#include <dctl/successor/copy/all_jumps.hpp>
#include <dctl/successor/copy/all_moves.hpp>
#include <dctl/successor/copy/king_jumps.hpp>
#include <dctl/successor/copy/king_moves.hpp>
#include <dctl/successor/copy/pawn_jumps.hpp>
#include <dctl/successor/copy/pawn_moves.hpp>
