#pragma once
#include <dctl/core/rules/checkers.hpp>
#include <dctl/core/rules/czech.hpp>
#include <dctl/core/rules/frisian.hpp>
#include <dctl/core/rules/international.hpp>
#include <dctl/core/rules/italian.hpp>
#include <dctl/core/rules/killer.hpp>
#include <dctl/core/rules/pool.hpp>
#include <dctl/core/rules/russian.hpp>
#include <dctl/core/rules/spanish.hpp>
#include <dctl/core/rules/thai.hpp>
#include <dctl/core/rules/type_traits.hpp>
