#pragma once
#include <dctl/successor/detect/primary_fwd.hpp>
#include <dctl/successor/detect/legal.hpp>
#include <dctl/successor/detect/jump.hpp>
#include <dctl/successor/detect/push.hpp>
#include <dctl/successor/detect/king_jump.hpp>
#include <dctl/successor/detect/king_push.hpp>
#include <dctl/successor/detect/pawn_jump.hpp>
#include <dctl/successor/detect/pawn_push.hpp>
