#pragma once
#include <iterator>                     // forward_iterator_tag, iterator, next
#include <boost/assert.hpp>             // BOOST_ASSERT
#include <boost/operators.hpp>          // equality_comparable1

namespace dctl {
namespace tree {

template<typename BackwardIterator>
bool is_link(BackwardIterator const& i, BackwardIterator const& j)
{
        return std::prev(i) == j;
}

template
<
        typename Node
>
struct backward_iterator
        // http://www.boost.org/doc/libs/1_52_0/libs/utility/operators.htm#chaining
        // use base class chaining to ensure Empty Base Optimization
:       boost::equality_comparable1< backward_iterator<Node>      // == !=
,       std::iterator<std::forward_iterator_tag, typename Node::value_type>
        >
{
private:
        // typedefs

        typedef typename Node::value_type T;
        typedef std::iterator<std::forward_iterator_tag, T> Base;

        // dependent names now in scope

        using Base::reference;  // T&
        using Base::pointer;    // T*

public:
        typedef Node& node_ref;
        typedef Node* node_ptr;

        // structors

        backward_iterator()
        :
                pnode_(nullptr)
        {}

        backward_iterator(node_ptr p)
        :
                pnode_(p)
        {}

        // modifiers

        backward_iterator& operator++()
        {
                pnode_ = pnode_->prev_;
                return *this;
        }

        backward_iterator operator++(int)
        {
                auto const old = *this;
                ++*this;
                return old;
        }

        friend void link(backward_iterator& i, backward_iterator& j)
        {
                i.pnode_->prev_ = j.pnode_;
                BOOST_ASSERT(is_link(i, j));
        }

        // queries

        reference operator*() const
        {
                return pnode_->value_;
        }

        pointer operator->() const
        {
                return &**this;
        }

        // predicates

        // operator!= automatically generated by boost::equality_comparable1
        friend bool operator==(backward_iterator const& lhs, backward_iterator const& rhs)
        {
                return lhs.pnode_ == rhs.pnode_;
        }

private:
        // representation

        node_ptr pnode_;
};

}       // namespace tree
}       // namespace dctl
