#pragma once
#include <iterator>                     // forward_iterator_tag, iterator, iterator_traits, next
#include <type_traits>                  // enable_if, is_same
#include <boost/assert.hpp>             // BOOST_ASSERT
#include <boost/operators.hpp>          // equality_comparable1
#include <dctl/tree/backward_link.hpp>  // backward_link
#include <dctl/tree/node.hpp>           // node

namespace dctl {
namespace tree {

template
<
        typename T
>
struct backward_iterator
        // http://www.boost.org/doc/libs/1_52_0/libs/utility/operators.htm#chaining
        // use base class chaining to ensure Empty Base Optimization
:       boost::equality_comparable1< backward_iterator<T>      // == !=
,       std::iterator<std::forward_iterator_tag, T>
        >
{
private:
        // dependent names now in scope

        typedef std::iterator<std::forward_iterator_tag, T> Base;
        using Base::value_type; // T
        using Base::pointer;    // T*
        using Base::reference;  // T&

        // typedefs

        typedef backward_iterator self_type;
        typedef backward_link link_type;
public:
        typedef node<link_type, value_type> node_type;
private:
        typedef link_type* link_ptr;
        typedef node_type* node_ptr;

public:
        // structors

        backward_iterator()
        :
                plink_()
        {}

        explicit backward_iterator(link_ptr p)
        :
                plink_(p)
        {}

        // modifiers

        self_type& operator++()
        {
                plink_ = plink_->prev_;
                return *this;
        }

        self_type operator++(int)
        {
                auto const old = *this;
                ++*this;
                return old;
        }

        void link(self_type& other)
        {
                plink_->connect(other.plink_);
                BOOST_ASSERT(this->is_linked(other));
        }

        // queries

        reference operator*() const
        {
                return static_cast<node_ptr>(plink_)->value_;
        }

        pointer operator->() const
        {
                return &**this;
        }

        // predicates

        // operator!= automatically generated by boost::equality_comparable1
        friend bool operator==(self_type const& lhs, self_type const& rhs)
        {
                return lhs.plink_ == rhs.plink_;
        }

private:
        // postcondition for link()

        bool is_linked(self_type const& other) const
        {
                return std::prev(this) == other;
        }

        // representation

        link_ptr plink_;
};

}       // namespace tree
}       // namespace dctl
