#pragma once
#include <iterator>                     // forward_iterator_tag, iterator
#include <boost/operators.hpp>          // equality_comparable1

namespace dctl {
namespace tree {
namespace iterator {

template
<
        typename Node
>
struct Forward
        // http://www.boost.org/doc/libs/1_52_0/libs/utility/operators.htm#chaining
        // use base class chaining to ensure Empty Base Optimization
:       boost::equality_comparable1< Forward<Node>      // == !=
,       std::iterator<std::forward_iterator_tag, typename Node::value_type>
        >
{
private:
        // typedefs

        typedef typename Node::value_type T;
        typedef std::iterator<std::forward_iterator_tag, T> Base;

        // dependent names now in scope

        using Base::reference;  // T&
        using Base::pointer;    // T*

public:
        typedef Node& node_ref;
        typedef Node* node_ptr;

        // structors

        Forward()
        :
                pnode_(nullptr)
        {}

        Forward(node_ptr p)
        :
                pnode_(p)
        {}

        // modifiers

        Forward& operator++()
        {
                pnode_ = pnode_->next();
                return *this;
        }

        Forward operator++(int)
        {
                auto const old = *this;
                ++*this;
                return old;
        }

        // queries

        reference operator*() const
        {
                return pnode_->value();
        }

        pointer operator->() const
        {
                return &**this;
        }

        // predicates

        // operator!= automatically generated by boost::equality_comparable1
        friend bool operator==(Forward const& lhs, Forward const& rhs)
        {
                return lhs.pnode_ == rhs.pnode_;
        }

private:
        // representation

        node_ptr pnode_;
};

}       // namespace iterator
}       // namespace tree
}       // namespace dctl
