#pragma once
#include <iterator>                     // advance, forward_iterator_tag, iterator, iterator_traits
#include <type_traits>                  // is_copy_constructible, is_default_constructible
#include <boost/mpl/assert.hpp>         // BOOST_MPL_ASSERT
#include <boost/operators.hpp>          // equality_comparable1

namespace dctl {
namespace tree {
namespace iterator {

template
<
        typename ForwardIterator,
        std::size_t N = 2
>
struct Stride
        // http://www.boost.org/doc/libs/1_52_0/libs/utility/operators.htm#chaining
        // use base class chaining to ensure Empty Base Optimization
:       boost::equality_comparable1< Stride<ForwardIterator, N> // == !=
,       std::iterator<std::forward_iterator_tag, typename std::iterator_traits<ForwardIterator>::value_type>
        >
{
private:
        // typedefs

        typedef typename std::iterator_traits<ForwardIterator>::value_type T;
        typedef std::iterator<std::forward_iterator_tag, T> Base;

        // dependent names now in scope

        using Base::reference;  // T&
        using Base::pointer;    // T*

public:
        // structors

        Stride()
        {
                BOOST_MPL_ASSERT((std::is_default_constructible<ForwardIterator>));
        }

        explicit Stride(ForwardIterator it)
        :
                fwd_(it)
        {
                BOOST_MPL_ASSERT((std::is_copy_constructible<ForwardIterator>));
        }

        // modifiers

        Stride& operator++()
        {
                std::advance(fwd_, N);
                return *this;
        }

        Stride operator++(int)
        {
                auto const old = *this;
                ++*this;
                return old;
        }

        // queries

        reference operator*() const
        {
                return *fwd_;
        }

        pointer operator->() const
        {
                return &**this;
        }

        // predicates

        // operator!= automatically generated by boost::equality_comparable1
        friend bool operator==(Stride const& lhs, Stride const& rhs)
        {
                return lhs.fwd_ == rhs.fwd_;
        }

private:
        // representation

        ForwardIterator fwd_;
};

}       // namespace iterator
}       // namespace tree
}       // namespace dctl
