#pragma once
#include <boost/operators.hpp>          // totally_ordered
#include <dctl/successor/value_fwd.hpp> // Value (primary template)

namespace dctl {
namespace successor {

// primary template
template<typename Rules>
struct Value
:
        // Curiously Recurring Template Pattern (CRTP)
        private boost::totally_ordered< Value<Rules> >  // < >= > <= == !=
{
        // predicates

        // operator!= automatically generated by boost::totally_ordered
        friend bool operator==(Value const & /* lhs */, Value const& /* rhs */)
        {
                return true;
        }

        // operator>=, operator>, operator<= automatically generated by boost::totally_ordered
        friend bool operator<(Value const & /* lhs */, Value const& /* rhs */)
        {
                return false;
        }
};

}       // namespace successor
}       // namespace dctl
