#pragma once
#include <cstddef>                      // size_t
#include <limits>                       // numeric_limits
#include <utility>                      // get, tuple
#include <boost/assert.hpp>             // BOOST_ASSERT
#include <boost/operators.hpp>          // totally_ordered
#include <dctl/successor/value_fwd.hpp> // Value (primary template)
#include <dctl/rules/spanish_fwd.hpp>   // Spanish

namespace dctl {
namespace successor {

// specialization for Spanish draughts
template<>
struct Value<rules::Spanish>
:
        // Curiously Recurring Template Pattern (CRTP)
        private boost::totally_ordered< Value<rules::Spanish> > // < >= > <= == !=
{
public:
        // structors

        Value()
        :
                data_() // std::tuple default constructor zero-intializes
        {
                BOOST_ASSERT(invariant());
        }

        // modifiers

        void increment(bool is_king)
        {
                BOOST_ASSERT(!full());
                num_kings() += is_king;
                ++num_pieces();
                BOOST_ASSERT(invariant());
        }

        void decrement(bool is_king)
        {
                BOOST_ASSERT(!empty(is_king));
                --num_pieces();
                num_kings() -= is_king;
                BOOST_ASSERT(invariant());
        }

        // queries

        std::size_t count() const
        {
                return num_pieces();
        }

        // predicates

        // operator>=, operator>, operator<= automatically generated by boost::totally_ordered
        friend bool operator<(Value const& lhs, Value const& rhs)
        {
                // delegate to std::tuple::operator<
                return lhs.data_ < rhs.data_;
        }

        // operator!= automatically generated by boost::totally_ordered
        friend bool operator==(Value const& lhs, Value const& rhs)
        {
                // delegate to std::tuple::operator==
                return lhs.data_ == rhs.data_;
        }

private:
        // modifiers

        std::size_t& num_pieces()
        {
                return std::get<num_pieces_>(data_);
        }

        std::size_t& num_kings()
        {
                return std::get<num_kings_>(data_);
        }

        // queries

        std::size_t const& num_pieces() const
        {
                return std::get<num_pieces_>(data_);
        }

        std::size_t const& num_kings() const
        {
                return std::get<num_kings_>(data_);
        }

        // predicates

        bool invariant() const
        {
                return (
                        (num_kings() <= num_pieces()) &&
                        (num_pieces() <= std::numeric_limits<std::size_t>::max())
                );
        }

        bool empty(bool is_king) const
        {
                return (is_king? num_kings() : num_pieces()) == 0;
        }

        bool full() const
        {
                return num_pieces() == std::numeric_limits<std::size_t>::max();
        }

        // representation

        enum { num_pieces_, num_kings_ };
        std::tuple<std::size_t, std::size_t> data_;
};

}       // namespace successor
}       // namespace dctl
