#pragma once
#include <dctl/board/mask/column.hpp>
#include <dctl/board/mask/initial.hpp>
#include <dctl/board/mask/jump_group.hpp>
#include <dctl/board/mask/jump_start.hpp>
#include <dctl/board/mask/promotion.hpp>
#include <dctl/board/mask/row.hpp>
#include <dctl/board/mask/squares.hpp>
#include <dctl/board/mask/king_targets.hpp>
